# Generated by Django 3.2.7 on 2021-11-14 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groop_action_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groop_id', models.CharField(max_length=20, verbose_name='グループID')),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日付')),
                ('history', models.CharField(max_length=1, verbose_name='結果')),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日付')),
                ('insert_people_ID', models.CharField(max_length=20, verbose_name='グループ名')),
            ],
        ),
        migrations.CreateModel(
            name='groop_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groop_id', models.CharField(max_length=20, verbose_name='グループID')),
                ('groop_name', models.CharField(max_length=50, verbose_name='グループ名')),
                ('target', models.CharField(max_length=50, verbose_name='目標')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='挿入日付')),
                ('insert_people_ID', models.CharField(max_length=20, verbose_name='挿入者ID')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日付')),
                ('update_people_ID', models.CharField(max_length=20, verbose_name='更新者ID')),
            ],
        ),
        migrations.CreateModel(
            name='groop_member_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groop_id', models.CharField(max_length=20, verbose_name='グループid')),
                ('member_id', models.CharField(max_length=20, verbose_name='メンバーid')),
                ('member_name', models.CharField(max_length=20, verbose_name='メンバー名')),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='挿入日付')),
                ('insert_people_id', models.CharField(max_length=20, verbose_name='挿入者ID')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日付')),
                ('update_people_id', models.CharField(max_length=20, verbose_name='更新者ID')),
            ],
        ),
    ]
